CREATE TABLE `data_platform_production_order_operation_data`
(
		`ProductionPlantBusinessPartner`          int(12) NOT NULL,
		`ProductionOrder`                         int(16) NOT NULL,
		`OrderInternalBillOfOperations`           varchar(4) NOT NULL,
`OrderIntBillOfOperationsItem


		`ProductionPlantBusinessPartner`          int(12) NOT NULL,
		`ProductionOrder`                         int(16) NOT NULL,
		`ProductionOrderSequence`                 varchar(4) NOT NULL,
		`ProductionOrderOperation`                varchar(4) NOT NULL,
		`OrderInternalBillOfOperations`           varchar(4) NOT NULL,
        `Reservation`                             int(16) DEFAULT NULL,
        `ReservationItem`                         int(6) DEFAULT NULL,
        `ProductGroup`                            varchar(9) DEFAULT NULL,
        `ComponentProduct`                        varchar(40) DEFAULT NULL,
		`ProductionPlant`                         varchar(4) DEFAULT NULL,
    	`ProductionOrderType`                     varchar(4) DEFAULT NULL,       
    	`ComponentProductRequirementDate`         date DEFAULT NULL,     
    	`ComponentProductRequirementTime`         time DEFAULT NULL,     
    	`ComponentProductIsMarkedForBackflush`    tinyint(1) DEFAULT NULL,   
		`PlannedOrder`                            int(16) DEFAULT NULL,
		`OrderID`                                 int(16) DEFAULT NULL,
		`OrderItem`                               int(6) DEFAULT NULL,
		`SortField`                               varchar(100) DEFAULT NULL,
	    `BillOfMaterial`                          int(16) DEFAULT NULL,
        `BOMItem`                                 int(6) DEFAULT NULL,
		`BOMItemDescription`                      varchar(200) DEFAULT NULL,
		`StorageLocation`                         varchar(4) DEFAULT NULL,
        `Batch`                                   varchar(10) DEFAULT NULL,
        `GoodsRecipientName`                      varchar(100) DEFAULT NULL,
        `UnloadingPointName`                      varchar(100) DEFAULT NULL,
        `ProductCompIsAlternativeItem`            tinyint(1) DEFAULT NULL,
        `ComponentScrapInPercent`                 float(6) DEFAULT NULL,
        `OperationScrapInPercent`                 float(6) DEFAULT NULL,
        `BaseUnit`                                varchar(3) DEFAULT NULL,
        `RequiredQuantity`                        float(15) DEFAULT NULL,
        `WithdrawnQuantity`                       float(15) DEFAULT NULL,
        `ConfirmedAvailableQuantity`              float(15) DEFAULT NULL,
        `ProductCompOriginalQuantity`             float(15) DEFAULT NULL,
        `Currency`                                varchar(3) DEFAULT NULL,
        `ComponentIsDeletion`                     tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`ProductionPlantBusinessPartner`, `ProductionOrder`, `ProductionOrderSequence`, `ProductionOrderOperation`, `OrderInternalBillOfOperations`),
	
    CONSTRAINT `DataPlatformProductionOrderComponentData_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionOrder`) REFERENCES `data_platform_production_order_header_data` (`ProductionPlantBusinessPartner`, `ProductionOrder`),
    CONSTRAINT `DataPlatformProductionOrderComponentDataReservation_fk` FOREIGN KEY (`Reservation`, `ReservationItem`) REFERENCES `data_platform_reservation_document_item_data` (`Reservation`, `ReservationItem`),
    CONSTRAINT `DataPlatformProductionOrderComponentDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`),
    CONSTRAINT `DataPlatformProductionOrderComponentDataComponentProduct_fk` FOREIGN KEY (`ComponentProduct`) REFERENCES `data_platform_product_master_general_data` (`Product`),
    CONSTRAINT `DataPlatformProductionOrderComponentDataComponentProductionPlant_fk` FOREIGN KEY (`ProductionPlant`) REFERENCES `data_platform_plant_general_data` (`ProductionPlant`),
    CONSTRAINT `DataPlatformProductionOrderComponentDataComponentPlannedOrder_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformProductionOrderComponentDataProductionOrder_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformProductionOrderComponentDataProductionBOM_fk` FOREIGN KEY (`BillOfMaterial`, `BOMItem`) REFERENCES `data_platform_orders_item_data` (`BillOfMaterial`, `BOMItem`),
    CONSTRAINT `DataPlatformProductionOrderComponentDataProductionStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`, `StorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProductionOrderComponentDataProductionBatch_fk` FOREIGN KEY (`Batch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Batch`),
    CONSTRAINT `DataPlatformProductionOrderComponentDataProductionCurrency_fk` FOREIGN KEY (`Currency`) REFERENCES `data_platform_currency_currency_data` (`Currency`),

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
