CREATE TABLE `data_platform_production_order_item_data`
(
		`ProductionOrder`                                int(16) NOT NULL,
    	`ProductionOrderItem`                            int(6) NOT NULL,
        `PrecedingProductionOrderItem`                   int(6) DEFAULT NULL,
      　`FollowingProductionOrderItem`                   int(6) DEFAULT NULL,
		`SupplyChainRelationshipID`                      int(16) NOT NULL,
		`SupplyChainRelationshipProductionPlantID`       int(4) NOT NULL,
		`SupplyChainRelationshipDeliveryID`              int(6) NOT NULL,
		`SupplyChainRelationshipDeliveryPlantID`         int(4) NOT NULL,
    	`ProductionOrderType`                            varchar(4) NOT NULL,
		`Product`                                        varchar(40) NOT NULL,
		`Buyer`		                                     int(12) NOT NULL,
		`Seller`    		                       	     int(12) NOT NULL,
		`ProductionPlantBusinessPartner`                 int(12) NOT NULL,
        `ProductionPlant`                                varchar(4) NOT NULL,
		`ProductionPlantStorageLocation`                 varchar(4) NOT NULL,
		`DeliverToParty` 		                  	     int(12) NOT NULL,
		`DeliverToPlant` 		              	  	     varchar(4) NOT NULL,
		`DeliverToPlantStorageLocation` 	      	     varchar(4) NOT NULL,
		`DeliverFromParty`   		              	     int(12) NOT NULL,
		`DeliverFromPlant`                	  	  	     varchar(4) NOT NULL,
		`DeliverFromPlantStorageLocation` 		  	     varchar(4) NOT NULL,
        `ProductBaseUnit`                          	     varchar(3) NOT NULL,
		`ProductProductionUnit`						     varchar(3) NOT NULL,
        `ProductDeliveryUnit`                      	     varchar(3) NOT NULL,
        `MRPArea`                                        varchar(10) DEFAULT NULL,
        `MRPController`                                  varchar(3) DEFAULT NULL,
        `ProductionVersion`                              int(16) DEFAULT NULL,
        `ProductionVersionItem`                          int(6) DEFAULT NULL,
        `BillOfMaterial`                                 int(16) NOT NULL,
        `Operations`                                     int(16) NOT NULL,
		`ProductionOrderQuantityInBaseUnit`        	     float(15) NOT NULL,
		`ProductionOrderQuantityInProductionUnit`  	     float(15) NOT NULL,
		`ProductionOrderQuantityInDeliveryUnit`          float(15) NOT NULL,
		`ProductionOrderPlannedScrapQtyInBaseUnit`		 float(15) DEFAULT NULL,
      　`ProductionOrderMinimumLotSizeQuantity`          float(15) NOT NULL,
        `ProductionOrderStandardLotSizeQuantity`         float(15) NOT NULL,
        `ProductionOrderMaximumLotSizeQuantity`          float(15) NOT NULL,
        `ProductionOrderLotSizeRoundingQuantity`         float(15) DEFAULT NULL,
        `ProductionOrderLotSizeIsFixed`                  tinyint(1) DEFAULT NULL,
		`ProductionOrderPlannedStartDate`                date NOT NULL,
		`ProductionOrderPlannedStartTime`                time NOT NULL,
		`ProductionOrderPlannedEndDate`                  date NOT NULL,
		`ProductionOrderPlannedEndTime`                  time NOT NULL,
		`ProductionOrderActualReleaseDate`               date DEFAULT NULL,
		`ProductionOrderActualReleaseTime`               time DEFAULT NULL,
		`ProductionOrderActualStartDate`                 date DEFAULT NULL,
		`ProductionOrderActualStartTime`                 time DEFAULT NULL,
		`ProductionOrderActualEndDate`                   date DEFAULT NULL,
		`ProductionOrderActualEndTime`                   time DEFAULT NULL,
		`ConfirmedYieldQuantityInBaseUnit`               float(15) DEFAULT NULL,
		`ConfirmedYieldQuantityInProductionUnit`         float(15) DEFAULT NULL,
		`ScrappedQuantityInBaseUnit`        	         float(15) DEFAULT NULL,
		`PlannedOrder`                                   int(16) DEFAULT NULL,
		`PlannedOrderItem`                               int(6) DEFAULT NULL,
		`OrderID`                                        int(16) DEFAULT NULL,
		`OrderItem`                                      int(6) DEFAULT NULL,     
        `ProductIsBatchManagedInProductionPlant`         tinyint(1) DEFAULT NULL,
        `BatchMgmtPolicyInProductionOrder`               varchar(4) DEFAULT NULL,
        `ProductionOrderTargetedBatch`                   varchar(10) DEFAULT NULL,
        `ProductionOrderTargetedBatchValidityStartDate`  date DEFAULT NULL,
        `ProductionOrderTargetedBatchValidityStartTime`  time DEFAULT NULL,
        `ProductionOrderTargetedBatchValidityEndDate`    date DEFAULT NULL,
        `ProductionOrderTargetedBatchValidityEndTime`    time DEFAULT NULL,
		`ProductionOrderPlannedScrapQtyInBaseUnit`       float(15) DEFAULT NULL,
        `ProductionOrderItemText`                        varchar(200) DEFAULT NULL,
		`CreationDate`                                   date NOT NULL,
		`CreationTime`                                   time NOT NULL,
		`LastChangeDate`                                 date NOT NULL,
		`LastChangeTime`                                 time NOT NULL,
    	`ComponentProductAvailabilityIsNotChecked`       tinyint(1) DEFAULT NULL,
    	`IsReleased`                  		  	         tinyint(1) DEFAULT NULL,
    	`IsPartiallyConfirmed`                           tinyint(1) DEFAULT NULL,
    	`IsConfirmed`                                    tinyint(1) DEFAULT NULL,
    	`IsLocked`                                       tinyint(1) DEFAULT NULL,
    	`IsCancelled`                                    tinyint(1) DEFAULT NULL,
    	`IsMarkedForDeletion`                            tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`ProductionOrder`, `ProductionOrderItem`),
	
    CONSTRAINT `DataPlatformProductionOrderItemData_fk` FOREIGN KEY (`ProductionOrder`) REFERENCES `data_platform_production_order_header_data` (`ProductionOrder`),
    CONSTRAINT `DataPlatformProductionOrderItemDataSCRID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_supply_chain_relationship_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
	CONSTRAINT `DataPlatformProductionOrderItemDataSCRProductionPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),
    CONSTRAINT `DataPlatformProductionOrderItemDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_supply_chain_relationship_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DataPlatformProductionOrderItemDataSCRDeliveryPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
    CONSTRAINT `DataPlatformProductionOrderItemDataPrecedingProductionOrderItem_fk` FOREIGN KEY (`ProductionOrder`, `PrecedingProductionOrderItem`) REFERENCES `data_platform_production_order_item_data` (`ProductionOrder`, `ProductionOrderItem`),
    CONSTRAINT `DataPlatformProductionOrderItemDataFollowingProductionOrderItem_fk` FOREIGN KEY (`ProductionOrder`, `FollowingProductionOrderItem`) REFERENCES `data_platform_production_order_item_data` (`ProductionOrder`, `ProductionOrderItem`),
    CONSTRAINT `DataPlatformProductionOrderItemDataProductionPlantStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProductionOrderItemDataDeliverFromPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `DeliverFromPlant`, `DeliverFromPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProductionOrderItemDataDeliverToPlantStorageLocation_fk` FOREIGN KEY (`DeliverToParty`, `DeliverToPlant`, `DeliverToPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProductionOrderItemDataProductBaseUnit_fk` FOREIGN KEY (`ProductBaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformProductionOrderItemDataProductProductionUnit_fk` FOREIGN KEY (`ProductProductionUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformProductionOrderItemDataProductDeliveryUnit_fk` FOREIGN KEY (`ProductDeliveryUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformProductionOrderItemDataProductionVersionItem_fk` FOREIGN KEY (`ProductionVersion`, `ProductionVersionItem`) REFERENCES `data_platform_production_version_item_data` (`ProductionVersion`, `ProductionVersionItem`),
    CONSTRAINT `DataPlatformProductionOrderItemDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`) REFERENCES `data_platform_bill_of_material_header_data` (`BillOfMaterial`),
    CONSTRAINT `DataPlatformProductionOrderItemDataOperations_fk` FOREIGN KEY (`Operations`) REFERENCES `data_platform_operations_header_data` (`Operations`),
    CONSTRAINT `DataPlatformProductionOrderItemDataPlannedOrderItem_fk` FOREIGN KEY (`PlannedOrder`, `PlannedOrderItem`) REFERENCES `data_platform_planned_order_item_data` (`PlannedOrder`, `PlannedOrderItem`),
    CONSTRAINT `DataPlatformProductionOrderItemDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformProductionOrderItemDataProductionOrderTargetedBatch_fk` FOREIGN KEY (`Product`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionOrderTargetedBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
