CREATE TABLE `data_platform_production_order_header_data`
(
		`ProductionPlantBusinessPartner`          int(12) NOT NULL,
		`ProductionOrder`                         int(16) NOT NULL,
    	`ProductionOrderType`                     varchar(4) DEFAULT NULL,    
    	`ProductionOrderIsReleased`               tinyint(1) DEFAULT NULL,    
    	`ProductionOrderIsConfirmed`              tinyint(1) DEFAULT NULL,
    	`ProductionOrderIsPartiallyConfirmed`     tinyint(1) DEFAULT NULL,   
		`CreationDate`                            date NOT NULL,       
		`LastChangeDate`                          date NOT NULL,
    	`ProductionOrderIsDeleted`                tinyint(1) DEFAULT NULL,   
    	`ProductionOrderIsLocked`                 tinyint(1) DEFAULT NULL, 
    	`ProductionOrderIsMarkedForDeletion`      tinyint(1) DEFAULT NULL,
    	`ProductionOrderHasGeneratedOperations`   tinyint(1) DEFAULT NULL,
    	`ProductAvailyIsNotChecked`               tinyint(1) DEFAULT NULL,   
		`Product`                                 varchar(40) DEFAULT NULL,
		`ProductionPlant`                         varchar(4) DEFAULT NULL,
		`StorageLocation`                         varchar(4) DEFAULT NULL,
        `GoodsRecipientName`                      varchar(100) DEFAULT NULL,
		`OrderInternalBillOfOperations`           int(3) DEFAULT NULL,
        `MRPArea`                                 varchar(10) DEFAULT NULL,
        `MRPController`                           varchar(3) DEFAULT NULL,
        `ProductionSupervisor`                    varchar(100) DEFAULT NULL,
        `ProductionVersion`                       varchar(4) DEFAULT NULL,
		`PlannedOrder`                            int(16) DEFAULT NULL,
		`OrderID`                                 int(16) DEFAULT NULL,
		`OrderItem`                               int(6) DEFAULT NULL,
		`ProductionOrderPlannedStartDate`         date DEFAULT NULL,
		`ProductionOrderPlannedStartTime`         time DEFAULT NULL,
		`ProductionOrderPlannedEndDate`           date DEFAULT NULL,
		`ProductionOrderPlannedEndTime`           time DEFAULT NULL,
		`ProductionOrderActualReleaseDate`        date DEFAULT NULL,
        `ProductionUnit`                          varchar(3) DEFAULT NULL,
        `TotalQuantity`                           float(15) NOT NULL,
        `ProductionOrderPlannedScrapQty`          float(15) DEFAULT NULL,
        `ProductionOrderConfirmedYieldQty`        float(15) DEFAULT NULL,
        `OrderItemText`                           varchar(200) DEFAULT NULL,

    PRIMARY KEY (`ProductionPlantBusinessPartner`, `ProductionOrder`),
	
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProduct_fk` FOREIGN KEY (`Product`) REFERENCES `data_platform_product_master_general_data` (`Product`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionPlant_fk` FOREIGN KEY (`ProductionPlant`) REFERENCES `data_platform_plant_general_data` (`Plant`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`, `StorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionPlannedOrder_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionOrder_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
