CREATE TABLE `data_platform_production_order_item_component_data`
(
		`ProductionOrder`                         int(16) NOT NULL,
     	`ProductionOrderItem`                     int(6) NOT NULL,
		`Operations`                              int(16) NOT NULL,
		`OperationsItem`                          int(6) NOT NULL,
	    `BillOfMaterial`                          int(16) NOT NULL,
        `BillOfMaterialItem`                      int(6) NOT NULL,
        `Reservation`                             int(16) DEFAULT NULL,
        `ReservationItem`                         int(6) DEFAULT NULL,
        `ComponentProduct`                        varchar(40) DEFAULT NULL,
    	`ComponentProductRequirementDate`         date DEFAULT NULL,
    	`ComponentProductRequirementTime`         time DEFAULT NULL,
    	`ComponentProductIsMarkedForBackflush`    tinyint(1) DEFAULT NULL,
        `ComponentProductBusinessPartner`         int(12) DEFAULT NULL,
        `StockConfirmationPlant`                  varchar(4) DEFAULT NULL,
		`PlannedOrder`                            int(16) DEFAULT NULL,
		`OrderID`                                 int(16) DEFAULT NULL,
		`OrderItem`                               int(6) DEFAULT NULL,
		`SortField`                               varchar(100) DEFAULT NULL,
		`BOMItemDescription`                      varchar(200) DEFAULT NULL,
		`StorageLocation`                         varchar(4) DEFAULT NULL,
        `Batch`                                   varchar(10) DEFAULT NULL,
        `GoodsRecipientName`                      varchar(100) DEFAULT NULL,
        `UnloadingPointName`                      varchar(100) DEFAULT NULL,
        `ProductCompIsAlternativeItem`            tinyint(1) DEFAULT NULL,
        `CostingPolicy`                           varchar(1) DEFAULT NULL,
        `PriceUnitQty`                            varchar(5) DEFAULT NULL,
        `StandardPrice`                           float(13) DEFAULT NULL,
        `MovingAveragePrice`                      float(13) DEFAULT NULL,
        `ComponentScrapInPercent`                 float(6) DEFAULT NULL,
        `OperationScrapInPercent`                 float(6) DEFAULT NULL,
        `BaseUnit`                                varchar(3) DEFAULT NULL,
        `RequiredQuantity`                        float(15) DEFAULT NULL,
        `WithdrawnQuantity`                       float(15) DEFAULT NULL,
        `ConfirmedAvailableQuantity`              float(15) DEFAULT NULL,
        `ProductCompOriginalQuantity`             float(15) DEFAULT NULL,
        `IsMarkedForDeletion`                     tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`ProductionOrder`, `ProductionOrderItem`, `Operations`, `OperationsItem`, `BillOfMaterial`, `BillOfMaterialItem`),
	
    CONSTRAINT `DataPlatformProductionOrderItemComponentData_fk` FOREIGN KEY (`ProductionOrder`, `ProductionOrderItem`) REFERENCES `data_platform_production_order_item_data` (`ProductionOrder`, `ProductionOrderItem`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`, `BillOfMaterialItem`) REFERENCES `data_platform_bill_of_material_item_data` (`BillOfMaterial`, `BillOfMaterialItem`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataOperations_fk` FOREIGN KEY (`Operations`, `OperationsItem`) REFERENCES `data_platform_operations_item_data` (`Operations`, `OperationsItem`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataReservation_fk` FOREIGN KEY (`Reservation`, `ReservationItem`) REFERENCES `data_platform_reservation_document_item_data` (`Reservation`, `ReservationItem`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataComponentProduct_fk` FOREIGN KEY (`ComponentProduct`) REFERENCES `data_platform_product_master_general_data` (`Product`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataComponentProductBusinessPartner_fk` FOREIGN KEY (`ComponentProductBusinessPartner`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataStockConfirmationPlant_fk` FOREIGN KEY (`StockConfirmationPlant`) REFERENCES `data_platform_plant_general_data` (`Plant`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataComponentProductionPlant_fk` FOREIGN KEY (`ProductionPlant`) REFERENCES `data_platform_plant_general_data` (`ProductionPlant`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataComponentPlannedOrder_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataProductionOrder_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataProductionBOM_fk` FOREIGN KEY (`BillOfMaterial`, `BillOfMaterialItem`) REFERENCES `data_platform_orders_item_data` (`BillOfMaterial`, `BillOfMaterialItem`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataProductionStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`, `StorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataProductionBatch_fk` FOREIGN KEY (`Batch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Batch`),
    CONSTRAINT `DataPlatformProductionOrderItemComponentDataProductionCurrency_fk` FOREIGN KEY (`Currency`) REFERENCES `data_platform_currency_currency_data` (`Currency`),
    
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
