CREATE TABLE `data_platform_production_order_item_operation_data`
(
      `ProductionOrder`                                   int(16) NOT NULL,
      `ProductionOrderItem`                               int(6) NOT NULL,
      `Operations`                                        int(16) NOT NULL,
      `OperationsItem`	                                  int(6) NOT NULL,
      `OperationID`                                       int(4) NOT NULL,
      `OperationType`                                     varchar(4) NOT NULL,
      `SupplyChainRelationshipID`                         int(16) NOT NULL,
      `SupplyChainRelationshipDeliveryID`                 int(6) NOT NULL,
      `SupplyChainRelationshipDeliveryPlantID`            int(4) NOT NULL,
      `SupplyChainRelationshipProductionPlantID`          int(4) NOT NULL,
      `Product`                                           varchar(40) NOT NULL,
      `Buyer`                                             int(12) NOT NULL,
      `Seller`                                            int(12) NOT NULL,
      `DeliverFromParty`                                  int(12) NOT NULL,
      `DeliverFromPlant`                                  varchar(4) NOT NULL,
      `DeliverToParty`                                    int(12) NOT NULL,
      `DeliverToPlant`                                    varchar(4) NOT NULL,
      `ProductionPlantBusinessPartner`                    int(12) NOT NULL,
      `ProductionPlant`                                   varchar(4) NOT NULL,
      `MRPArea`                                           varchar(10) DEFAULT NULL,
      `MRPController`                                     varchar(3) DEFAULT NULL,
      `ProductionVersion`                                 int(16) DEFAULT NULL,
      `ProductionVersionItem`                             int(6) DEFAULT NULL,
      `Sequence`                                          int(4) NOT NULL,
      `SequenceText`                                      varchar(200) DEFAULT NULL,
      `OperationText`                                     varchar(200) NOT NULL,
      `ProductBaseUnit`                                   varchar(3) NOT NULL,
      `ProductProductionUnit`                             varchar(3) NOT NULL,
      `ProductOperationUnit`                              varchar(3) NOT NULL,
      `ProductDeliveryUnit`                               varchar(3) NOT NULL,
      `StandardLotSizeQuantity`                           float(15) NOT NULL,
      `MinimumLotSizeQuantity`                            float(15) NOT NULL,
      `MaximumLotSizeQuantity`                            float(15) NOT NULL,
      `OperationPlannedQuantityInBaseUnit`                float(15) NOT NULL,
      `OperationPlannedQuantityInProductionUnit`          float(15) NOT NULL,
      `OperationPlannedQuantityInOperationUnit`           float(15) NOT NULL,
      `OperationPlannedQuantityInDeliveryUnit`            float(15) NOT NULL,
      `OperationPlannedScrapInPercent`                    float(7) DEFAULT NULL,
      `ResponsiblePlannerGroup`                           varchar(3) DEFAULT NULL,
      `PlainLongText`                                     varchar(1000) DEFAULT NULL,
      `WorkCenter`                                        int(16) NOT NULL,
      `CapacityCategory`                                  varchar(20) DEFAULT NULL,
      `OperationCostingRelevancyType`                     varchar(1) DEFAULT NULL,
      `OperationSetupType`                                varchar(2) DEFAULT NULL,
      `OperationSetupGroupCategory`                       varchar(10) DEFAULT NULL,
      `OperationSetupGroup`                               varchar(10) DEFAULT NULL,
      `MaximumWaitDuration`                               float(11) DEFAULT NULL,
      `StandardWaitDuration`                              float(11) DEFAULT NULL,
      `MinimumWaitDuration`                               float(11) DEFAULT NULL,
      `WaitDurationUnit`                                  varchar(3) DEFAULT NULL,
      `MaximumQueueDuration`                              float(11) DEFAULT NULL,
      `StandardQueueDuration`                             float(11) DEFAULT NULL,
      `MinimumQueueDuration`                              float(11) DEFAULT NULL,
      `QueueDurationUnit`                                 varchar(3) DEFAULT NULL,
      `MaximumMoveDuration`                               float(11) DEFAULT NULL,
      `StandardMoveDuration`                              float(11) DEFAULT NULL,
      `MinimumMoveDuration`                               float(11) DEFAULT NULL,
      `MoveDurationUnit`                                  varchar(3) DEFAULT NULL,
      `StandardDeliveryDuration`                          float(11) DEFAULT NULL,
      `StandardDeliveryDurationUnit`                      varchar(3) DEFAULT NULL,
      `CostElement`                                       varchar(10) DEFAULT NULL,
      `OperationErlstSchedldExecStrtDte`                  date DEFAULT NULL,
      `OperationErlstSchedldExecStrtTme`                  time DEFAULT NULL,
      `OperationErlstSchedldExecEndDate`                  date DEFAULT NULL,
      `OperationErlstSchedldExecEndTme`                   time DEFAULT NULL,
      `OperationActualExecutionStartDate`                 date DEFAULT NULL,
      `OperationActualExecutionStartTime`                 time DEFAULT NULL,
      `OperationActualExecutionEndDate`                   date DEFAULT NULL,
      `OperationActualExecutionEndTime`                   time DEFAULT NULL,
      `OperationConfirmedYieldQuantityInBaseUnit`         float(15) DEFAULT NULL,
      `OperationConfirmedYieldQuantityInProductionUnit`   float(15) DEFAULT NULL,
      `OperationConfirmedYieldQuantityInOperationUnit`    float(15) DEFAULT NULL,
      `CreationDate`                                      date NOT NULL,
      `CreationTime`                                      time NOT NULL,
      `LastChangeDate`                                    date NOT NULL,
      `LastChangeTime`                                    time NOT NULL,
      `IsReleased`                                        tinyint(1) DEFAULT NULL,
      `IsPartiallyConfirmed`                              tinyint(1) DEFAULT NULL,
      `IsConfirmed`                                       tinyint(1) DEFAULT NULL,
      `IsLocked`                                          tinyint(1) DEFAULT NULL,
      `IsCancelled`                                       tinyint(1) DEFAULT NULL,
      `IsMarkedForDeletion`                               tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`ProductionOrder`, `ProductionOrderItem`, `Operations`, `OperationsItem`, `OperationID`),

    CONSTRAINT `DPFMProductionOrderItemOperationData_fk` FOREIGN KEY (`ProductionOrder`, `ProductionOrderItem`) REFERENCES `data_platform_production_order_item_data` (`ProductionOrder`, `ProductionOrderItem`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataOperationID_fk` FOREIGN KEY (`Operations`, `OperationsItem`, `OperationID`) REFERENCES `data_platform_operations_item_operation_data` (`Operations`, `OperationsItem`, `OperationID`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataSCRID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_scr_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_scr_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
--     CONSTRAINT `DPFMProductionOrderItemOperationDataSCRDeliveryPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_scr_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
--     CONSTRAINT `DPFMProductionOrderItemOperationDataSCRProductionPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`) REFERENCES `data_platform_scr_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataProductionVersionItem_fk` FOREIGN KEY (`ProductionVersion`, `ProductionVersionItem`) REFERENCES `data_platform_production_version_item_data` (`ProductionVersion`, `ProductionVersionItem`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataProductBaseUnit_fk` FOREIGN KEY (`ProductBaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataProductProductionUnit_fk` FOREIGN KEY (`ProductProductionUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataProductOperationUnit_fk` FOREIGN KEY (`ProductOperationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataProductDeliveryUnit_fk` FOREIGN KEY (`ProductDeliveryUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataWorkCenter_fk` FOREIGN KEY (`WorkCenter`) REFERENCES `data_platform_work_center_general_data` (`WorkCenter`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataWaitDurationUnit_fk` FOREIGN KEY (`WaitDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataQueueDurationUnit_fk` FOREIGN KEY (`QueueDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataMoveDurationUnit_fk` FOREIGN KEY (`MoveDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMProductionOrderItemOperationDataStandardDDUnit_fk` FOREIGN KEY (`StandardDeliveryDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
