CREATE TABLE `data_platform_production_order_item_data`
(
		`ProductionOrder`                            int(16) NOT NULL,
    	`ProductionOrderItem`                        int(6) NOT NULL,
        `PrecedingProductionOrderItem`               int(6) DEFAULT NULL,
      　`FollowingProductionOrderItem`               int(6) DEFAULT NULL,
		`SupplyChainRelationshipID`                  int(16) NOT NULL,
		`SupplyChainRelationshipProductionPlantID`   int(4) NOT NULL,
		`SupplyChainRelationshipDeliveryID`          int(6) NOT NULL,
		`SupplyChainRelationshipDeliveryPlantID`     int(4) NOT NULL,
		`CreationDate`                               date NOT NULL,
		`CreationTime`                               time NOT NULL,
		`LastChangeDate`                             date NOT NULL,
		`LastChangeTime`                             time NOT NULL,
    	`IsReleased`                  		  	     tinyint(1) DEFAULT NULL,
    	`IsPartiallyConfirmed`                       tinyint(1) DEFAULT NULL,
    	`IsConfirmed`                                tinyint(1) DEFAULT NULL,
    	`IsLocked`                                   tinyint(1) DEFAULT NULL,
    	`IsCancelled`                                tinyint(1) DEFAULT NULL,
    	`IsMarkedForDeletion`                        tinyint(1) DEFAULT NULL,
    	`ProductionOrderHasGeneratedOperations`      tinyint(1) DEFAULT NULL,
    	`ProductAvailabilityIsNotChecked`            tinyint(1) DEFAULT NULL,
		`Product`                                    varchar(40) DEFAULT NULL,
		`BusinessPartner`                            int(12) NOT NULL,
        `Plant`                                      varchar(4) NOT NULL,
		`StorageLocation`                            varchar(4) DEFAULT NULL,
        `MRPArea`                                    varchar(10) DEFAULT NULL,
        `MRPController`                              varchar(3) DEFAULT NULL,
        `ProductionSupervisor`                       varchar(100) DEFAULT NULL,
        `ProductionVersion`                          int(16) DEFAULT NULL,
        `ProductionVersionItem`                      int(6) DEFAULT NULL,
        `BillOfMaterial`                             int(16) NOT NULL,
        `Operations`                                 int(16) NOT NULL,
		`PlannedOrder`                               int(16) DEFAULT NULL,
		`PlannedOrderItem`                           int(6) DEFAULT NULL,
		`OrderID`                                    int(16) DEFAULT NULL,
		`OrderItem`                                  int(6) DEFAULT NULL,
      　`MinimumLotSizeQuantity`                     float(15) DEFAULT NULL,
        `StandardLotSizeQuantity`                    float(15) DEFAULT NULL,
        `LotSizeRoundingQuantity`                    float(15) DEFAULT NULL,
        `MaximumLotSizeQuantity`                     float(15) DEFAULT NULL,
        `LotSizeIsFixed`                             tinyint(1) DEFAULT NULL,
		`ProductionOrderPlannedStartDate`            date DEFAULT NULL,
		`ProductionOrderPlannedStartTime`            time DEFAULT NULL,
		`ProductionOrderPlannedEndDate`              date DEFAULT NULL,
		`ProductionOrderPlannedEndTime`              time DEFAULT NULL,
		`ProductionOrderActualReleaseDate`           date DEFAULT NULL,
		`ProductionOrderActualReleaseTime`           time DEFAULT NULL,
		`ProductionOrderActualStartDate`             date DEFAULT NULL,
		`ProductionOrderActualStartTime`             time DEFAULT NULL,
		`ProductionOrderActualEndDate`               date DEFAULT NULL,
		`ProductionOrderActualEndTime`               time DEFAULT NULL,
        `ProductionOrderBatch`                       varchar(10) DEFAULT NULL,
        `BaseUnit`                                   varchar(3) DEFAULT NULL,
        `ProductionUnit`                             varchar(3) DEFAULT NULL,
        `TotalQuantity`                              float(15) NOT NULL,
        `PlannedScrapQuantity`                       float(15) DEFAULT NULL,
        `ConfirmedYieldQuantity`                     float(15) DEFAULT NULL,
        `ProductionOrderItemText`                    varchar(200) DEFAULT NULL,

    PRIMARY KEY (`ProductionOrder`, `ProductionOrderItem`),
	
    CONSTRAINT `DataPlatformProductionOrderItemData_fk` FOREIGN KEY (`ProductionOrder`) REFERENCES `data_platform_production_order_header_data` (`ProductionOrder`),
    CONSTRAINT `DataPlatformProductionOrderItemDataPrecedingProductionOrderItem_fk` FOREIGN KEY (`ProductionOrder`, `PrecedingProductionOrderItem`) REFERENCES `data_platform_production_order_item_data` (`ProductionOrder`, `ProductionOrderItem`),
    CONSTRAINT `DataPlatformProductionOrderItemDataFollowingProductionOrderItem_fk` FOREIGN KEY (`ProductionOrder`, `FollowingProductionOrderItem`) REFERENCES `data_platform_production_order_item_data` (`ProductionOrder`, `ProductionOrderItem`),
    CONSTRAINT `DataPlatformProductionOrderItemDataProduct_fk` FOREIGN KEY (`Product`, `BusinessPartner`, `Plant`) REFERENCES `data_platform_product_master_bp_plant_data` (`Product`, `BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformProductionOrderItemDataStorageLocation_fk` FOREIGN KEY (`BusinessPartner`, `Plant`, `StorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProductionOrderItemDataProductionVersion_fk` FOREIGN KEY (`ProductionVersion`, `ProductionVersionItem`) REFERENCES `data_platform_production_version_item_data` (`ProductionVersion`, `ProductionVersionItem`),
    CONSTRAINT `DataPlatformProductionOrderItemDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`) REFERENCES `data_platform_bill_of_material_header_data` (`BillOfMaterial`),
    CONSTRAINT `DataPlatformProductionOrderItemDataOperations_fk` FOREIGN KEY (`Operations`) REFERENCES `data_platform_operations_header_data` (`Operations`),
    CONSTRAINT `DataPlatformProductionOrderItemDataPlannedOrder_fk` FOREIGN KEY (`PlannedOrder`, `PlannedOrderItem`) REFERENCES `data_platform_planned_order_item_data` (`PlannedOrder`, `PlannedOrderItem`),
    CONSTRAINT `DataPlatformProductionOrderItemDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformProductionOrderItemDataProductionOrderBatch_fk` FOREIGN KEY (`Product`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionOrderBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DataPlatformProductionOrderItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformProductionOrderItemDataProductionUnit_fk` FOREIGN KEY (`ProductionUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
