CREATE TABLE `data_platform_production_order_header_data`
(
		`ProductionOrder`                         int(16) NOT NULL,
    	`ProductionOrderType`                     varchar(4) DEFAULT NULL,
		`CreationDate`                            date NOT NULL,
		`LastChangeDate`                          date NOT NULL,
    	`HeaderIsReleased`                        tinyint(1) DEFAULT NULL,
    	`HeaderIsPartiallyConfirmed`              tinyint(1) DEFAULT NULL,
    	`HeaderIsConfirmed`                       tinyint(1) DEFAULT NULL,
    	`HeaderIsLocked`                          tinyint(1) DEFAULT NULL,
    	`HeaderIsMarkedForDeletion`               tinyint(1) DEFAULT NULL,
		`Product`                                 varchar(40) DEFAULT NULL,
		`OwnerProductionPlant`                    varchar(4) NOT NULL,
		`OwnerProductionPlantBusinessPartner`     int(12) NOT NULL,
		`OwnerProductionPlantStorageLocation`     varchar(4) DEFAULT NULL,
        `MRPArea`                                 varchar(10) DEFAULT NULL,
        `MRPController`                           varchar(3) DEFAULT NULL,
        `ProductionSupervisor`                    varchar(100) DEFAULT NULL,
        `ProductionVersion`                       int(16) DEFAULT NULL,
		`PlannedOrder`                            int(16) DEFAULT NULL,
		`OrderID`                                 int(16) DEFAULT NULL,
		`OrderItem`                               int(6) DEFAULT NULL,
		`ProductionOrderPlannedStartDate`         date DEFAULT NULL,
		`ProductionOrderPlannedStartTime`         time DEFAULT NULL,
		`ProductionOrderPlannedEndDate`           date DEFAULT NULL,
		`ProductionOrderPlannedEndTime`           time DEFAULT NULL,
		`ProductionOrderActualReleaseDate`        date DEFAULT NULL,
		`ProductionOrderActualReleaseTime`        time DEFAULT NULL,
		`ProductionOrderActualStartDate`          date DEFAULT NULL,
		`ProductionOrderActualStartTime`          time DEFAULT NULL,
		`ProductionOrderActualEndDate`            date DEFAULT NULL,
		`ProductionOrderActualEndTime`            time DEFAULT NULL,
        `ProductionUnit`                          varchar(3) DEFAULT NULL,
        `TotalQuantity`                           float(15) NOT NULL,
        `PlannedScrapQuantity`                    float(15) DEFAULT NULL,
        `ConfirmedYieldQuantity`                  float(15) DEFAULT NULL,
        `ProductionOrderHeaderText`               varchar(200) DEFAULT NULL,

    PRIMARY KEY (`ProductionOrder`),
	
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProduct_fk` FOREIGN KEY (`Product`) REFERENCES `data_platform_product_master_general_data` (`Product`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionPlant_fk` FOREIGN KEY (`OwnerProductionPlant`) REFERENCES `data_platform_plant_general_data` (`Plant`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionStorageLocation_fk` FOREIGN KEY (`OwnerProductionPlantBusinessPartner`, `OwnerProductionPlant`, `OwnerProductionPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionPlannedOrder_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionOrder_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
