CREATE TABLE `data_platform_production_order_item_operation_component_data`
(
    `ProductionOrder`                                            int(16) NOT NULL,
    `ProductionOrderItem`                                        int(6) NOT NULL,
    `Operations`                                                 int(16) NOT NULL,
    `OperationsItem`                                             int(6) NOT NULL,
    `OperationID`                                                int(4) NOT NULL,
    `BillOfMaterial`                                             int(16) NOT NULL,
    `BillOfMaterialItem`                                         int(6) NOT NULL,
    `SupplyChainRelationshipID`                                  int(16) NOT NULL,
    `SupplyChainRelationshipDeliveryID`                          int(6) NOT NULL,
    `SupplyChainRelationshipDeliveryPlantID`                     int(4) NOT NULL,
    `ProductionPlantBusinessPartner`                             int(12) NOT NULL,
    `ProductionPlant`                                            varchar(4) NOT NULL,
    `ComponentProduct`                                           varchar(40) NOT NULL,
    `ComponentProductBuyer`                                      int(12) NOT NULL,
    `ComponentProductSeller`                                     int(12) NOT NULL,
    `ComponentProductDeliverToParty`                             int(12) NOT NULL,
    `ComponentProductDeliverToPlant`                             varchar(4) NOT NULL,
    `ComponentProductDeliverFromParty`                           int(12) NOT NULL,
    `ComponentProductDeliverFromPlant`                           varchar(4) NOT NULL,
    `ComponentProductDeliverToPartyInOperation`                  int(12) NOT NULL,
    `ComponentProductDeliverToPlantInOperation`                  varchar(4) NOT NULL,
    `ComponentProductDeliverFromPartyInOperation`                int(12) NOT NULL,
    `ComponentProductDeliverFromPlantInOperation`                varchar(4) NOT NULL,
    `ComponentProductRequirementDateInOperation`                 date NOT NULL,
    `ComponentProductRequirementTimeInOperation`                 time NOT NULL,
    `ComponentProductPlannedQuantityInBaseUnitInOperation`       float(15) NOT NULL,
    `ComponentProductPlannedQuantityInDeliveryUnitInOperation`   float(15) NOT NULL,
    `ComponentProductPlannedScrapInPercentInOperation`           float(7) DEFAULT NULL,
    `ComponentProductBaseUnit`                                   varchar(3) NOT NULL,
    `ComponentProductDeliveryUnit`                               varchar(3) NOT NULL,
    `ComponentProductIsMarkedForBackflush`                       tinyint(1) DEFAULT NULL,
    `MRPArea`                                                    varchar(10) DEFAULT NULL,
    `MRPController`                                              varchar(3) DEFAULT NULL,
    `ProductionVersion`                                          int(16) DEFAULT NULL,
    `ProductionVersionItem`                                      int(6) DEFAULT NULL,
    `ComponentProductReservation`                                int(16) DEFAULT NULL,
    `ComponentProductReservationItem`                            int(4) DEFAULT NULL,
    `CreationDate`                                               date NOT NULL,
    `CreationTime`                                               date NOT NULL,
    `LastChangeDate`                                             date NOT NULL,
    `LastChangeTime`                                             date NOT NULL,
    `IsReleased`                  	                             tinyint(1) DEFAULT NULL,
    `IsLocked`                                                   tinyint(1) DEFAULT NULL,
    `IsCancelled`                                                tinyint(1) DEFAULT NULL,
    `IsMarkedForDeletion`                                        tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`ProductionOrder`, `ProductionOrderItem`, `Operations`, `OperationsItem`, `OperationID`, `BillOfMaterial`, `BillOfMaterialItem`),

    CONSTRAINT `DPFMProductionOrderItemOperationComponentData_fk` FOREIGN KEY (`ProductionOrder`, `ProductionOrderItem`, `Operations`, `OperationsItem`, `OperationID`) REFERENCES `data_platform_production_order_item_operation_data` (`ProductionOrder`, `ProductionOrderItem`, `Operations`, `OperationsItem`, `OperationID`),
    CONSTRAINT `DPFMProductionOrderItemOperationComponentDataBOMItem_fk` FOREIGN KEY (`ProductionOrder`, `ProductionOrderItem`, `BillOfMaterial`, `BillOfMaterialItem`) REFERENCES `data_platform_production_order_item_component_data` (`ProductionOrder`, `ProductionOrderItem`, `BillOfMaterial`, `BillOfMaterialItem`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
  