CREATE TABLE `data_platform_production_order_header_data`
(
		`ProductionOrder`                            			int(16) NOT NULL,
		`SupplyChainRelationshipID`                  			int(16) NOT NULL,
		`SupplyChainRelationshipProductionPlantID`   			int(4) NOT NULL,
		`SupplyChainRelationshipDeliveryID`          			int(6) NOT NULL,
		`SupplyChainRelationshipDeliveryPlantID`     			int(4) NOT NULL,
    	`ProductionOrderType`                        			varchar(4) NOT NULL,
		`Product`                                    			varchar(40) NOT NULL,
		`Buyer`   		                         	 			int(12) NOT NULL,
		`Seller`        		                   	 			int(12) NOT NULL,
		`OwnerProductionPlantBusinessPartner`     	 			int(12) NOT NULL,
		`OwnerProductionPlant`                    	 			varchar(4) NOT NULL,
		`OwnerProductionPlantStorageLocation`     	 			varchar(4) NOT NULL,
		`DepartureDeliverFromParty`   		       	 			int(12) NOT NULL,
		`DepartureDeliverFromPlant`                	 			varchar(4) NOT NULL,
		`DepartureDeliverFromPlantStorageLocation` 	 			varchar(4) NOT NULL,
		`DestinationDeliverToParty`           		 			int(12) NOT NULL,
		`DestinationDeliverToPlant`               	 			varchar(4) NOT NULL,
		`DestinationDeliverToPlantStorageLocation` 	 			varchar(4) NOT NULL,
		`ProductBaseUnit`							 			varchar(3) NOT NULL,
        `MRPArea`                                    			varchar(10) DEFAULT NULL,
        `MRPController`                              			varchar(3) DEFAULT NULL,
        `ProductionVersion`                       	 			int(16) DEFAULT NULL,
        `BillOfMaterial`                          	 			int(16) NOT NULL,
        `Operations`                              	 			int(16) NOT NULL,
		`ProductionOrderQuantityInBaseUnit`        	  			float(15) NOT NULL,
		`ProductionOrderQuantityInDepartureProductionUnit`		float(15) NOT NULL,
		`ProductionOrderQuantityInDestinationProductionUnit`	float(15) NOT NULL,
		`ProductionOrderQuantityInDepartureDeliveryUnit` 		float(15) NOT NULL,
		`ProductionOrderQuantityInDestinationDeliveryUnit`		float(15) NOT NULL,
		`ProductionOrderDepartureProductionUnit`	      		varchar(3) NOT NULL,
		`ProductionOrderDestinationProductionUnit`    	  		varchar(3) NOT NULL,
		`ProductionOrderDepartureDeliveryUnit`		      		varchar(3) NOT NULL,
		`ProductionOrderDestinationDeliveryUnit`    	  		varchar(3) NOT NULL,
		`ProductionOrderPlannedScrapQtyInBaseUnit` 	  			float(15) DEFAULT NULL,
		`ProductionOrderPlannedStartDate`            			date NOT NULL,
		`ProductionOrderPlannedStartTime`            			time NOT NULL,
		`ProductionOrderPlannedEndDate`              			date NOT NULL,
		`ProductionOrderPlannedEndTime`              			time NOT NULL,
		`ProductionOrderActualReleaseDate`           			date DEFAULT NULL,
		`ProductionOrderActualReleaseTime`           			time DEFAULT NULL,
		`ProductionOrderActualStartDate`             			date DEFAULT NULL,
		`ProductionOrderActualStartTime`             			time DEFAULT NULL,
		`ProductionOrderActualEndDate`               			date DEFAULT NULL,
		`ProductionOrderActualEndTime`               			time DEFAULT NULL,
		`PlannedOrder`                               			int(16) DEFAULT NULL,
		`OrderID`                                   			int(16) DEFAULT NULL,
		`OrderItem`                                  			int(6) DEFAULT NULL,
        `ProductionOrderHeaderText`                  			varchar(200) DEFAULT NULL,
		`CreationDate`                               			date NOT NULL,
		`CreationTime`                               			time NOT NULL,
		`LastChangeDate`                             			date NOT NULL,
		`LastChangeTime`                             			time NOT NULL,
    	`IsReleased`                                 			tinyint(1) DEFAULT NULL,
    	`IsPartiallyConfirmed`                       			tinyint(1) DEFAULT NULL,
    	`IsConfirmed`                                			tinyint(1) DEFAULT NULL,
    	`IsLocked`                                   			tinyint(1) DEFAULT NULL,
    	`IsCancelled`                                			tinyint(1) DEFAULT NULL,
    	`IsMarkedForDeletion`                        			tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`ProductionOrder`),
	
    CONSTRAINT `DataPlatformProductionOrderHeaderDataSCRID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_supply_chain_relationship_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
	CONSTRAINT `DataPlatformProductionOrderHeaderDataSCRProductionPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `OwnerProductionPlantBusinessPartner`, `OwnerProductionPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),
	CONSTRAINT `DataPlatformProductionOrderHeaderDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DestinationDeliverToParty`, `DepartureDeliverFromParty`) REFERENCES `data_platform_supply_chain_relationship_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataSCRDeliveryPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DestinationDeliverToParty`, `DepartureDeliverFromParty`, `DestinationDeliverToPlant`, `DepartureDeliverFromPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataOwnerProductionPlantStorageLocation_fk` FOREIGN KEY (`OwnerProductionPlantBusinessPartner`, `OwnerProductionPlant`, `OwnerProductionPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
	CONSTRAINT `DataPlatformProductionOrderHeaderDataDepartureDeliverFromPlantStorageLocation_fk` FOREIGN KEY (`DepartureDeliverFromParty`, `DepartureDeliverFromPlant`, `DepartureDeliverFromPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataDestinationDeliverToPlantStorageLocation_fk` FOREIGN KEY (`DestinationDeliverToParty`, `DestinationDeliverToPlant`, `DestinationDeliverToPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductBaseUnit_fk` FOREIGN KEY (`ProductBaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
	CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionVersion_fk` FOREIGN KEY (`ProductionVersion`) REFERENCES `data_platform_production_version_header_data` (`ProductionVersion`),
	CONSTRAINT `DataPlatformProductionOrderHeaderDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`) REFERENCES `data_platform_bill_of_material_header_data` (`BillOfMaterial`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataOperations_fk` FOREIGN KEY (`Operations`) REFERENCES `data_platform_operations_header_data` (`Operations`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionOrderDepartureProductionUnit_fk` FOREIGN KEY (`ProductionOrderDepartureProductionUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionOrderDestinationProductionUnit_fk` FOREIGN KEY (`ProductionOrderDestinationProductionUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
	CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionOrderDepartureDeliveryUnit_fk` FOREIGN KEY (`ProductionOrderDepartureDeliveryUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataProductionOrderDestinationDeliveryUnit_fk` FOREIGN KEY (`ProductionOrderDestinationDeliveryUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
	CONSTRAINT `DataPlatformProductionOrderHeaderDataPlannedOrder_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformProductionOrderHeaderDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
